(() => {
'use strict';
const VERSION='0.3.0', STORAGE_KEY='tamil-psalms-editor-v0.3-psalm1', LEGACY_STORAGE_KEY='tamil-psalms-editor-v0.2-psalm1', LABELS=['a','b','c','d','e','f','g','h','i'];
const STATUS_LABEL={UNREVIEWED:'Not reviewed',AI_PROPOSED:'AI proposed',HUMAN_APPROVED:'Human approved',HUMAN_REJECTED:'Human rejected',HUMAN_MODIFIED:'Human modified',NEEDS_DISCUSSION:'Needs discussion','not-started':'Not started','in-progress':'In progress',disputed:'Disputed',approved:'Approved'};
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x)), now=()=>new Date().toISOString(), uniq=a=>[...new Set(a)], shortLine=id=>String(id||'').replace('PSA.1.','');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const setEq=(a,b)=>{const x=[...(a||[])].sort(),y=[...(b||[])].sort();return x.length===y.length&&x.every((v,i)=>v===y[i])};
const DATA=clone(window.PSALM_DATA);
const canonicalHebrewId=id=>String(id||'').replace(/^h-(\d+)-(\d+)-(\d+)$/,(_,p,v,n)=>`PSA.${p}.${v}.H${String(n).padStart(3,'0')}`);
const canonicalTamilId=id=>String(id||'').replace(/^t-(\d+)-([^\-]+)-(\d+)$/,(_,p,v,n)=>`PSA.${p}.${v}.T${String(n).padStart(3,'0')}`);
Object.values(DATA.hebrew).forEach(v=>(v.words||[]).forEach(w=>w.id=canonicalHebrewId(w.id)));
Object.values(DATA.alignment).forEach(v=>{(v.tokens||[]).forEach(t=>t.id=canonicalTamilId(t.id));(v.alignments||[]).forEach(a=>{a.hebrewTokenId=canonicalHebrewId(a.hebrewTokenId);a.tamilTokenIds=(a.tamilTokenIds||[]).map(canonicalTamilId)})});
DATA.lines.forEach(l=>{l.hebrewTokenIds=(l.hebrewTokenIds||[]).map(canonicalHebrewId);l.tamilTokenIds=(l.tamilTokenIds||[]).map(canonicalTamilId)});
const REVIEW_STATUSES=new Set(['UNREVIEWED','AI_PROPOSED','HUMAN_APPROVED','HUMAN_REJECTED','HUMAN_MODIFIED','NEEDS_DISCUSSION']);
const oldStatusToV03=s=>REVIEW_STATUSES.has(s)?s:({approved:'HUMAN_APPROVED',reviewed:'HUMAN_APPROVED','needs-review':'NEEDS_DISCUSSION',disputed:'NEEDS_DISCUSSION',annotated:'AI_PROPOSED',draft:'AI_PROPOSED','not-started':'UNREVIEWED'}[s]||'UNREVIEWED');
const parallelTypeToV03=t=>({Synonymous:'SYNONYMOUS',Antithetic:'ANTITHETIC','Complementary / Synthetic':'SYNTHETIC','Climactic / Staircase':'CLIMACTIC','Comparative / Emblematic':'EMBLEMATIC',Consequential:'CONSEQUENTIAL',Repetition:'REPETITION',Other:'OTHER',Uncertain:'UNCERTAIN'}[t]||String(t||'UNCERTAIN').toUpperCase());
const structureTypeToV03=t=>String(t||'OTHER').replace(/\s+/g,'_').toUpperCase();
const confidenceToV03=c=>String(c||'MEDIUM').toUpperCase();
function recordBase(status='UNREVIEWED',origin='machine',method='psalms-editor-v0.3'){const at=now();return{status,provenance:{origin,method},revision:1,revisions:[],createdAt:at,updatedAt:at}}
function tamilProjection(tokenIds=[],text='',status='UNREVIEWED',method='alignment-projection'){return{tokenIds:[...tokenIds],text,method,status,coverage:tokenIds.length?1:0}}
function sourceRevision(){const s=DATA.meta.sources;return{hebrew:{version:s.hebrew.label,archiveSha256:s.hebrew.sha256},tamil:{label:s.tamil.label,sha256:s.tamil.sha256},english:{label:s.english.label,sha256:s.english.sha256},analysisRunId:'psalm-1-editor-v0.3'}}
const hebrewById={},hebrewOrderByVerse={},tamilById={},tamilOrderByVerse={},alignByHebrew={},alignByTamil={};
Object.entries(DATA.hebrew).forEach(([v,o])=>{hebrewOrderByVerse[v]=o.words.map(w=>w.id);o.words.forEach((w,i)=>hebrewById[w.id]={...w,verse:v,index:i})});
Object.entries(DATA.alignment).forEach(([v,o])=>{tamilOrderByVerse[v]=(o.tokens||[]).map(t=>t.id);(o.tokens||[]).forEach((t,i)=>tamilById[t.id]={...t,verse:v,index:i});(o.alignments||[]).forEach(a=>{if(a.hebrewTokenId)(alignByHebrew[a.hebrewTokenId]||=[]).push(a);(a.tamilTokenIds||[]).forEach(id=>(alignByTamil[id]||=[]).push(a))})});
function initialSegments(){return DATA.lines.map(l=>({id:l.id,verse:String(l.verse),lineIndex:l.lineIndex,unitType:'colon',hebrewTokenIds:[...(l.hebrewTokenIds||[])],tamil:tamilProjection(l.tamilTokenIds,l.tamilText),english:{text:(l.englishText||'').replace(/\*/g,''),method:'source-line'},...recordBase()}))}
function defaultState(){return{schemaVersion:VERSION,book:'PSA',psalm:1,revision:sourceRevision(),psalmStatus:'not-started',segments:initialSegments(),parallelGroups:[],components:[],structures:[],notes:[],validation:{runAt:now(),issues:[]},migration:null,updatedAt:now()}}
let state=loadState(),history=[clone(state)],historyIndex=0,selection={lines:new Set(),hebrew:new Set(),tamil:new Set(),focus:null},activeGroupId=null,editingComponentId=null,editingComponentLabel=null,editingParallelId=null,editingStructureId=null,activeSegmentId=null,lastValidation=[];
function loadState(){try{const current=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(current?.schemaVersion===VERSION)return normalizeV03(current).state;const legacy=JSON.parse(localStorage.getItem(LEGACY_STORAGE_KEY)||'null');return legacy?.schemaVersion==='0.2.0'?migrateV02(legacy).state:defaultState()}catch{return defaultState()}}
function persist(){state.updatedAt=now();try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saveState').textContent='Saved locally'}catch{$('saveState').textContent='Use Export to save'}}
function commit(fn,msg='Saved'){fn();recomputePsalmStatus();validateState();persist();history=history.slice(0,historyIndex+1);history.push(clone(state));historyIndex++;renderAll();toast(msg)}
function undo(){if(historyIndex<=0)return;state=clone(history[--historyIndex]);persist();renderAll();toast('Undone')}
function redo(){if(historyIndex>=history.length-1)return;state=clone(history[++historyIndex]);persist();renderAll();toast('Redone')}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1800)}
function segmentById(id){return state.segments.find(x=>x.id===id)}function groupById(id){return state.parallelGroups.find(x=>x.id===id)}function componentById(id){return state.components.find(x=>x.id===id)}function structureById(id){return state.structures.find(x=>x.id===id)}
function sortedSegments(){return[...state.segments].sort((a,b)=>+a.verse-+b.verse||(a.lineIndex||0)-(b.lineIndex||0)||a.id.localeCompare(b.id))}function segmentsForVerse(v){return sortedSegments().filter(x=>x.verse===String(v))}function groupIdsForLine(id){return state.parallelGroups.filter(g=>(g.lineIds||[]).includes(id)).map(g=>g.id)}
function nextEntityId(prefix,list){const used=new Set(list.map(x=>x.id));let n=1;used.forEach(id=>{const m=String(id).match(new RegExp('^'+prefix+'(\\d+)$'));if(m)n=Math.max(n,+m[1]+1)});let id;do{id=prefix+String(n++).padStart(3,'0')}while(used.has(id));return id}
function nextSegmentId(v){const used=new Set(state.segments.map(x=>x.id));let n=1;state.segments.filter(x=>x.verse===String(v)).forEach(x=>{const m=x.id.match(/\.L(\d+)$/);if(m)n=Math.max(n,+m[1]+1)});let id;do{id=`PSA.1.${v}.L${n++}`}while(used.has(id));return id}
function ordered(ids,order){const s=new Set(ids||[]);return(order||[]).filter(id=>s.has(id))}function hebrewText(ids){return(ids||[]).map(id=>hebrewById[id]?.text).filter(Boolean).join(' ')}function tamilIds(e){return e?.tamil?.tokenIds||[]}function tamilText(e){return e?.tamil?.text||''}function componentLabels(id,lang){return state.components.filter(c=>(lang==='hebrew'?c.hebrewTokenIds:tamilIds(c)).includes(id)).map(c=>c.label)}
function snapshot(e){const s=clone(e);delete s.revisions;return s}function revise(e,changes,change='Edited'){e.revisions||=[];e.revisions.push({revision:e.revision||1,at:now(),change,status:e.status,snapshot:snapshot(e)});const wasApproved=e.status==='HUMAN_APPROVED';Object.assign(e,changes);e.revision=(e.revision||1)+1;e.updatedAt=now();if(wasApproved)e.status='NEEDS_DISCUSSION'}function setStatus(e,s){e.status=oldStatusToV03(s);e.updatedAt=now()}
function recomputePsalmStatus(){const all=[...state.segments,...state.parallelGroups,...state.components,...state.structures],meaningful=state.parallelGroups.length+state.components.length+state.structures.length+state.segments.filter(s=>s.status!=='UNREVIEWED').length;if(!meaningful){state.psalmStatus='not-started';return}if(all.some(x=>x.status==='NEEDS_DISCUSSION')){state.psalmStatus='disputed';return}if(!validateStateFor(state).some(i=>i.severity==='error')&&all.length&&all.every(x=>x.status==='HUMAN_APPROVED'))state.psalmStatus='approved';else state.psalmStatus='in-progress'}
function normalizeBase(e,origin='migration'){const old=e.status;e.status=oldStatusToV03(old);if(old&&!REVIEW_STATUSES.has(old))e.legacyStatus=e.legacyStatus||old;e.provenance=e.provenance||{origin,method:'psalms-editor-migration'};e.revision=Math.max(1,+e.revision||1);e.revisions=(e.revisions||[]).map(r=>({revision:Math.max(1,+r.revision||1),at:r.at||r.savedAt||now(),change:r.change||r.reason||'Migrated revision',...(r.status?{status:oldStatusToV03(r.status)}:{}),...(r.snapshot?{snapshot:r.snapshot}:{})}));e.createdAt=e.createdAt||e.updatedAt||now();e.updatedAt=e.updatedAt||e.createdAt;return e}
function normalizeV03(input){const x=clone(input),report=[];x.schemaVersion=VERSION;x.book='PSA';x.psalm=+x.psalm||1;x.revision=x.revision||sourceRevision();x.psalmStatus=x.psalmStatus||'not-started';x.segments=Array.isArray(x.segments)?x.segments:initialSegments();['parallelGroups','components','structures','notes'].forEach(k=>{if(!Array.isArray(x[k]))x[k]=[]});x.segments.forEach((s,i)=>{normalizeBase(s);s.verse=String(s.verse||s.id?.split('.')[2]||1);s.lineIndex=s.lineIndex||i+1;s.unitType=s.unitType||'colon';s.hebrewTokenIds=(s.hebrewTokenIds||[]).map(canonicalHebrewId);s.tamil=s.tamil||tamilProjection((s.tamilTokenIds||[]).map(canonicalTamilId),s.tamilText||'',s.status,'migration');s.tamil.tokenIds=(s.tamil.tokenIds||[]).map(canonicalTamilId);s.tamil.status=oldStatusToV03(s.tamil.status||s.status);s.english=s.english||{text:s.englishText||'',method:'migration'};delete s.tamilTokenIds;delete s.tamilText;delete s.englishText;delete s.source});x.parallelGroups.forEach(g=>{normalizeBase(g);g.type=parallelTypeToV03(g.type);if(g.confidence)g.confidence=confidenceToV03(g.confidence)});x.components.forEach(c=>{normalizeBase(c);c.hebrewTokenIds=(c.hebrewTokenIds||[]).map(canonicalHebrewId);c.tamil=c.tamil||tamilProjection((c.tamilTokenIds||[]).map(canonicalTamilId),'',c.status,'migration');c.tamil.tokenIds=(c.tamil.tokenIds||[]).map(canonicalTamilId);c.tamil.status=oldStatusToV03(c.tamil.status||c.status);delete c.tamilTokenIds});x.structures.forEach(s=>{normalizeBase(s);s.type=structureTypeToV03(s.type);s.parentId=s.parentId||null});x.notes=x.notes.map((n,i)=>{if(typeof n==='string')n={text:n};normalizeBase(n);n.id=n.id||`N${String(i+1).padStart(3,'0')}`;n.kind=n.kind||'migration';n.targetIds=n.targetIds||[];return n});x.validation=x.validation||{runAt:now(),issues:[]};x.updatedAt=x.updatedAt||now();delete x.sourceVersion;return{state:x,report}}
function migrateV02(input){const result=normalizeV03(input);result.state.migration={fromVersion:'0.2.0',importedAt:now(),report:[{kind:'ok',text:'Upgraded v0.2 records, projections, token IDs, review states, provenance, and revision metadata to v0.3.'}]};result.report=result.state.migration.report;return result}
function segmentsOf(s,v){return(s.segments||[]).filter(x=>String(x.verse)===String(v))}
function componentKey(c){return JSON.stringify({h:[...(c.hebrewTokenIds||[])].sort(),t:[...tamilIds(c)].sort(),g:c.parallelGroupId||null})}
function validateStateFor(s){const issues=[],add=(severity,code,message,entityType='file',entityId='PSA.1',scholarly=false)=>issues.push({severity,code,message,entityType,entityId:entityId||'PSA.1',scholarly}),uniqueCheck=(a,t)=>{const seen=new Set();a.forEach(e=>{if(seen.has(e.id))add('error','ID_DUPLICATE',`Duplicate ${t} ID: ${e.id}.`,t,e.id);seen.add(e.id)})};uniqueCheck(s.segments,'segment');uniqueCheck(s.parallelGroups,'parallelGroup');uniqueCheck(s.components,'component');uniqueCheck(s.structures,'structure');const segIds=new Set(s.segments.map(x=>x.id)),grpIds=new Set(s.parallelGroups.map(x=>x.id)),structIds=new Set(s.structures.map(x=>x.id));
s.parallelGroups.forEach(g=>{if((g.lineIds||[]).length<2)add('error','GROUP_INCOMPLETE',`${g.id} has fewer than two segments.`,'parallelGroup',g.id);(g.lineIds||[]).forEach(id=>{if(!segIds.has(id))add('error','GROUP_INCOMPLETE',`${g.id} refers to missing segment ${id}.`,'parallelGroup',g.id)})});
s.components.forEach(c=>{if(!c.parallelGroupId)add('warning','COMPONENT_UNATTACHED',`${c.id} (${c.label}) is not attached to a parallel group.`,'component',c.id);else if(!grpIds.has(c.parallelGroupId))add('error','COMPONENT_UNATTACHED',`${c.id} refers to missing group ${c.parallelGroupId}.`,'component',c.id);(c.hebrewTokenIds||[]).forEach(id=>{if(!hebrewById[id])add('error','COMPONENT_INVALID_TOKEN',`${c.id} refers to missing Hebrew token ${id}.`,'component',c.id)});tamilIds(c).forEach(id=>{if(!tamilById[id])add('error','COMPONENT_INVALID_TOKEN',`${c.id} refers to missing Tamil token ${id}.`,'component',c.id)})});
for(let i=0;i<s.components.length;i++)for(let j=i+1;j<s.components.length;j++){const a=s.components[i],b=s.components[j];if(componentKey(a)!==componentKey(b))continue;if(a.label===b.label)add('warning','COMPONENT_DUPLICATE',`${a.id} and ${b.id} select the same tokens with label ${a.label}.`,'component',b.id);else add('warning','COMPONENT_CONFLICT',`${a.id} (${a.label}) and ${b.id} (${b.label}) select the same tokens.`,'component',b.id)}
const lg={};s.parallelGroups.forEach(g=>(g.lineIds||[]).forEach(id=>(lg[id]||=[]).push(g.id)));Object.entries(lg).filter(([,v])=>v.length>1).forEach(([id,gs])=>add('warning','GROUP_LINE_IN_MULTIPLE_GROUPS',`${id} belongs to multiple groups: ${gs.join(', ')}.`,'segment',id,true));
s.structures.forEach(st=>{if(!segIds.has(st.startLineId)||!segIds.has(st.endLineId))add('error','STRUCTURE_INVALID_RANGE',`${st.id} has a missing start/end segment.`,'structure',st.id);if(st.parentId&&!structIds.has(st.parentId))add('error','STRUCTURE_ORPHAN_CHILD',`${st.id} refers to missing parent ${st.parentId}.`,'structure',st.id);if(st.parentId===st.id)add('error','STRUCTURE_ORPHAN_CHILD',`${st.id} cannot parent itself.`,'structure',st.id)});
Object.keys(DATA.hebrew).filter(v=>/^\d+$/.test(v)).forEach(v=>{const counts={};segmentsOf(s,v).forEach(seg=>(seg.hebrewTokenIds||[]).forEach(id=>counts[id]=(counts[id]||0)+1));hebrewOrderByVerse[v].forEach(id=>{if(!counts[id])add('warning','SEGMENT_TOKEN_UNCOVERED',`Psalm 1:${v} Hebrew token ${hebrewById[id].text} (${id}) is not assigned to a poetic segment.`,'segment',segmentsOf(s,v)[0]?.id||`PSA.1.${v}.L1`);if(counts[id]>1)add('error','SEGMENT_TOKEN_DUPLICATE',`Hebrew token ${id} occurs in ${counts[id]} segments in Psalm 1:${v}.`,'segment',segmentsOf(s,v)[0]?.id||`PSA.1.${v}.L1`)})});return issues}
function validateState(){lastValidation=validateStateFor(state);state.validation={runAt:now(),issues:clone(lastValidation)};return lastValidation}
function migrateV01(input){
  const out=defaultState(),report=[];
  out.segments=initialSegments().map(s=>({...s,status:(input.lineStatuses||{})[s.id]||'not-started'}));
  out.parallelGroups=(input.parallelGroups||[]).map(g=>({...clone(g),revision:1,revisions:[],updatedAt:g.createdAt||now()}));
  out.components=(input.components||[]).map(c=>({...clone(c),revision:1,revisions:[],updatedAt:c.createdAt||now()}));
  const old=input.structures||[],map={};
  out.structures=old.map((s,i)=>{const legacy=s.id||`legacy-${i+1}`,id='S'+String(i+1).padStart(3,'0');(map[legacy]||=[]).push(id);return{...clone(s),legacyId:legacy,id,revision:1,revisions:[],updatedAt:s.createdAt||now()}});
  let ambiguous=0;out.structures.forEach((s,i)=>{const p=old[i]?.parentId;if(!p){s.parentId=null;return}const m=map[p]||[];if(m.length===1)s.parentId=m[0];else{s.parentId=null;ambiguous++}});
  const dup=Object.entries(map).filter(([,v])=>v.length>1);
  report.push({kind:'ok',text:`Preserved ${out.parallelGroups.length} parallel groups, ${out.components.length} components, ${out.structures.length} structures and ${out.segments.length} segments.`});
  if(dup.length)report.push({kind:'warn',text:'Repaired duplicate legacy structure IDs; all v0.3 structure IDs are unique.'});
  if(ambiguous)report.push({kind:'warn',text:`Cleared ${ambiguous} ambiguous parent reference(s) caused by duplicate legacy IDs. No structure text was deleted.`});
  out.notes=clone(input.notes||[]);out.psalmStatus='in-progress';
  const normalized=normalizeV03(out).state,issues=validateStateFor(normalized),count=code=>issues.filter(i=>i.code===code).length;
  [['COMPONENT_UNATTACHED','component(s) are not attached to a parallel group'],['COMPONENT_DUPLICATE','duplicate component pair(s) detected'],['COMPONENT_CONFLICT','conflicting component pair(s) detected'],['GROUP_LINE_IN_MULTIPLE_GROUPS','segment(s) occur in more than one parallel group']].forEach(([c,t])=>{const n=count(c);if(n)report.push({kind:'warn',text:`${n} ${t}; none were deleted.`})});
  const missing=DATA.lines.filter(l=>!Object.prototype.hasOwnProperty.call(input.lineStatuses||{},l.id)).length;if(missing)report.push({kind:'warn',text:`${missing} scaffold segment(s) had no saved line status and were imported as Not reviewed.`});
  normalized.migration={fromVersion:input.schemaVersion||'0.1.x',importedAt:now(),report:clone(report)};return{state:normalized,report}
}
function renderAll(){validateState();renderVerseList();renderInspector();renderActiveGroupSelect();renderComponentButtons();renderSegmentation();renderParallelPicker();renderParallelGroups();renderComponents();renderStructureSelects();renderStructures();renderValidation();renderDataset();renderProgress();$('undoBtn').disabled=historyIndex<=0;$('redoBtn').disabled=historyIndex>=history.length-1}
function switchTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===id));renderAll()}
function selectToken(lang,id){const s=selection[lang];s.has(id)?s.delete(id):s.add(id);selection.focus={type:'token',lang,id};renderVerseList();renderInspector();renderComponentButtons()}
function selectLine(id){selection.lines.has(id)?selection.lines.delete(id):selection.lines.add(id);selection.focus={type:'line',id};renderVerseList();renderParallelPicker();renderInspector()}
function clearSelection(){selection={lines:new Set(),hebrew:new Set(),tamil:new Set(),focus:null};renderAll()}
function renderVerseList(){const root=$('verseList');root.innerHTML='';Object.keys(DATA.hebrew).filter(v=>/^\d+$/.test(v)).sort((a,b)=>+a-+b).forEach(v=>{const segs=segmentsForVerse(v),statuses=segs.map(s=>s.status),vs=statuses.length&&statuses.every(x=>x==='approved')?'approved':statuses.some(x=>x==='disputed')?'disputed':statuses.some(x=>x!=='not-started')?'in-progress':'not-started',card=document.createElement('article');card.className='verse-card';card.innerHTML=`<div class="verse-head"><strong>Psalm 1:${v}</strong><span class="verse-status">${esc(STATUS_LABEL[vs])}</span></div>`;const grid=document.createElement('div');grid.className='source-grid';
const hcol=document.createElement('div');hcol.className='source-col';hcol.innerHTML='<div class="source-label"><span>HEBREW • UHB 2.1.32</span><span>RTL</span></div>';const ht=document.createElement('div');ht.className='hebrew';DATA.hebrew[v].words.forEach(w=>{const sp=document.createElement('span');sp.className='token aligned';sp.dataset.token=w.id;sp.dataset.lang='hebrew';sp.textContent=w.text;if(selection.hebrew.has(w.id))sp.classList.add('selected');if(componentLabels(w.id,'hebrew').length)sp.classList.add('has-component');sp.title='Click for lemma, Strong’s, morphology and Tamil alignment';ht.append(sp,document.createTextNode(' '))});hcol.appendChild(ht);
const tcol=document.createElement('div');tcol.className='source-col';tcol.innerHTML='<div class="source-label"><span>TAMIL • IRV</span><span>READ ONLY</span></div>';const tl=document.createElement('div');tl.className='tamil-lines';(DATA.tamilLines[v]||[]).forEach(x=>{const d=document.createElement('span');d.className='poetry-line';d.textContent=x.text;tl.appendChild(d)});tcol.appendChild(tl);const tray=document.createElement('div');tray.className='help';tray.style.marginTop='8px';(DATA.alignment[v]?.tokens||[]).forEach(t=>{const sp=document.createElement('span');sp.className='token aligned';sp.dataset.token=t.id;sp.dataset.lang='tamil';sp.textContent=t.text;if(selection.tamil.has(t.id))sp.classList.add('selected');if(componentLabels(t.id,'tamil').length)sp.classList.add('has-component');tray.append(sp,document.createTextNode(' '))});tcol.appendChild(tray);
const ecol=document.createElement('div');ecol.className='source-col';ecol.innerHTML='<div class="source-label"><span>ENGLISH • ESV</span><span>LOCAL REFERENCE</span></div>';const el=document.createElement('div');el.className='english-lines';(DATA.englishLines[v]||[]).forEach(x=>{const d=document.createElement('span');d.className='poetry-line';d.textContent=x.text.replace(/\*/g,'');el.appendChild(d)});ecol.appendChild(el);grid.append(hcol,tcol,ecol);card.appendChild(grid);
const sw=document.createElement('div');sw.className='working-lines';sw.innerHTML='<div class="working-title">POETIC SEGMENTS • ANNOTATION LAYER</div>';segs.forEach(s=>{const gs=groupIdsForLine(s.id),r=document.createElement('div');r.className='working-row';r.dataset.line=s.id;if(selection.lines.has(s.id))r.classList.add('selected');if(activeGroupId&&gs.includes(activeGroupId))r.classList.add('in-active-group');r.innerHTML=`<span class="line-ref">${esc(shortLine(s.id))}<span class="line-groups">${gs.map(g=>`<span class="group-mini">${esc(g)}</span>`).join('')}</span></span><span class="line-text">${esc(tamilText(s)||hebrewText(s.hebrewTokenIds))}</span><span class="status-badge ${esc(s.status)}">${esc(STATUS_LABEL[s.status]||s.status)}</span>`;sw.appendChild(r)});card.appendChild(sw);root.appendChild(card)});root.querySelectorAll('.token').forEach(e=>e.onclick=ev=>{ev.stopPropagation();selectToken(e.dataset.lang,e.dataset.token)});root.querySelectorAll('.working-row').forEach(e=>e.onclick=()=>selectLine(e.dataset.line))}
function renderInspector(){const title=$('inspectorTitle'),body=$('inspectorBody');body.className='';if(editingComponentId){const c=componentById(editingComponentId);title.textContent=`Editing ${c?.id||''}`;body.innerHTML=`<p class="help">Toggle Hebrew/Tamil tokens in the text, choose label/group, then save. Revision ${c?.revision||1}.</p>`;return}if(selection.focus?.type==='token'){const{lang,id}=selection.focus;if(lang==='hebrew'){const w=hebrewById[id],als=alignByHebrew[id]||[],t=uniq(als.flatMap(a=>a.tamilTokenIds||[]).map(x=>tamilById[x]?.text).filter(Boolean));title.textContent=w.text;body.innerHTML=`<dl class="inspector-kv"><dt>Lemma</dt><dd dir="rtl">${esc(w.lemma)}</dd><dt>Strong</dt><dd>${esc(w.strong)}</dd><dt>Morphology</dt><dd>${esc(w.morph)}</dd><dt>Tamil</dt><dd>${esc(t.join(' · ')||'Unaligned')}</dd><dt>Components</dt><dd>${esc(componentLabels(id,'hebrew').join(', ')||'—')}</dd></dl>`}else{const t=tamilById[id],als=alignByTamil[id]||[],hs=uniq(als.map(a=>a.hebrewTokenId).filter(Boolean)).map(x=>hebrewById[x]);title.textContent=t?.text||id;body.innerHTML=`<dl class="inspector-kv"><dt>Hebrew</dt><dd dir="rtl">${esc(hs.map(h=>h.text).join(' · ')||'Unaligned')}</dd><dt>Lemma</dt><dd dir="rtl">${esc(hs.map(h=>h.lemma).join(' · ')||'—')}</dd><dt>Strong</dt><dd>${esc(hs.map(h=>h.strong).join(' · ')||'—')}</dd><dt>Components</dt><dd>${esc(componentLabels(id,'tamil').join(', ')||'—')}</dd></dl>`}}else if(selection.focus?.type==='line'){const s=segmentById(selection.focus.id);title.textContent=shortLine(s.id);body.innerHTML=`<dl class="inspector-kv"><dt>Verse</dt><dd>Psalm 1:${s.verse}</dd><dt>Hebrew</dt><dd dir="rtl">${esc(hebrewText(s.hebrewTokenIds))}</dd><dt>Tamil</dt><dd>${esc(tamilText(s)||'—')}</dd><dt>Status</dt><dd>${esc(STATUS_LABEL[s.status]||s.status)}</dd></dl>`}else{title.textContent='Nothing selected';body.className='muted';body.textContent='Click a Hebrew/Tamil token or poetic segment.'}}
function renderActiveGroupSelect(){const s=$('activeGroupSelect');if(activeGroupId&&!groupById(activeGroupId))activeGroupId=null;s.innerHTML='<option value="">Choose a group…</option>'+state.parallelGroups.map(g=>`<option value="${g.id}">${esc(g.id)} · ${esc(g.type)}</option>`).join('');s.value=activeGroupId||''}
function renderComponentButtons(){const r=$('componentButtons');r.innerHTML='';LABELS.forEach(l=>{const b=document.createElement('button');b.textContent=l;if(editingComponentLabel===l)b.classList.add('current');b.disabled=!editingComponentId&&(!activeGroupId||!selection.hebrew.size);b.onclick=()=>editingComponentId?(editingComponentLabel=l,renderComponentButtons()):createComponent(l);r.appendChild(b)});const edit=!!editingComponentId;$('componentEditorTitle').textContent=edit?`Edit ${editingComponentId}`:'Add component';$('componentEditActions').classList.toggle('hidden',!edit);$('componentEditStatus').classList.toggle('hidden',!edit);if(edit){const c=componentById(editingComponentId);$('componentEditStatus').textContent=STATUS_LABEL[c.status]||c.status;$('componentEditStatus').className=`pill ${c.status}`;$('componentHelp').textContent='Approved annotations can be corrected. Saving an approved edit creates a Needs discussion revision.';$('componentNote').value=c.note||''}else{$('componentHelp').textContent='Select Hebrew tokens (and optional Tamil projection), choose a group, then a–i.'}}
function createComponent(label){if(!activeGroupId){toast('Choose or create an active parallel group first');return}if(!selection.hebrew.size){toast('Select at least one Hebrew token first');return}const id=nextEntityId('C',state.components),note=$('componentNote').value.trim();commit(()=>state.components.push({id,label,parallelGroupId:activeGroupId,hebrewTokenIds:[...selection.hebrew],tamil:tamilProjection([...selection.tamil],selection.tamil.size?[...selection.tamil].map(x=>tamilById[x]?.text).filter(Boolean).join(' '):'','HUMAN_MODIFIED','human'),note,...recordBase('HUMAN_MODIFIED','human','editor')}),`${id} (${label}) added`);selection.hebrew.clear();selection.tamil.clear();selection.focus=null;$('componentNote').value=''}
function startEditComponent(id){const c=componentById(id);if(!c)return;editingComponentId=id;editingComponentLabel=c.label;activeGroupId=c.parallelGroupId||null;selection.hebrew=new Set(c.hebrewTokenIds||[]);selection.tamil=new Set(tamilIds(c));selection.lines=new Set();selection.focus=null;switchTab('workbench')}
function cancelComponentEdit(){editingComponentId=null;editingComponentLabel=null;selection.hebrew.clear();selection.tamil.clear();selection.focus=null;renderAll()}
function saveComponentEdit(){const c=componentById(editingComponentId);if(!c)return;if(!editingComponentLabel){toast('Choose a label');return}if(!activeGroupId){toast('Choose a parallel group');return}if(!selection.hebrew.size){toast('Select at least one Hebrew token');return}const projection=tamilProjection([...selection.tamil],[...selection.tamil].map(x=>tamilById[x]?.text).filter(Boolean).join(' '),'HUMAN_MODIFIED','human'),changes={label:editingComponentLabel,parallelGroupId:activeGroupId,hebrewTokenIds:[...selection.hebrew],tamil:projection,note:$('componentNote').value.trim()},changed=c.label!==changes.label||c.parallelGroupId!==changes.parallelGroupId||!setEq(c.hebrewTokenIds,changes.hebrewTokenIds)||!setEq(tamilIds(c),projection.tokenIds)||(c.note||'')!==changes.note;if(!changed){toast('No changes to save');return}const was=c.status==='HUMAN_APPROVED';commit(()=>revise(c,changes,'Component edited'),`${c.id} updated${was?' · Needs discussion':''}`);cancelComponentEdit()}
function deleteComponent(id){if(!confirm(`Delete component ${id}?`))return;commit(()=>state.components=state.components.filter(c=>c.id!==id),`${id} deleted`);if(editingComponentId===id)cancelComponentEdit()}
function reopenComponent(id){const c=componentById(id);commit(()=>revise(c,{},'Reopened for discussion'),`${id} reopened`)}
function restoreComponentRevision(id,index){const c=componentById(id),r=c?.revisions?.[index];if(!r||!r.snapshot)return;commit(()=>{const current=snapshot(c),revs=c.revisions;c.revisions.push({revision:c.revision||1,at:now(),change:'Before restoring earlier revision',status:c.status,snapshot:current});Object.assign(c,clone(r.snapshot));c.id=id;c.revisions=revs;c.revision=Math.max(...revs.map(x=>x.revision||0),c.revision||0)+1;c.status='NEEDS_DISCUSSION';c.updatedAt=now()},`${id} restored as new revision`);$('historyDialog').close()}
function renderSegmentation(){const root=$('segmentationList');root.innerHTML='';Object.keys(DATA.hebrew).filter(v=>/^\d+$/.test(v)).sort((a,b)=>+a-+b).forEach(v=>{const wrap=document.createElement('section');wrap.className='seg-verse';wrap.innerHTML=`<div class="segment-top"><strong>Psalm 1:${v}</strong><button class="small" data-new>+ New segment</button></div>`;const src=document.createElement('div');src.className='seg-source';DATA.hebrew[v].words.forEach(w=>{const sp=document.createElement('span');sp.className='token';sp.textContent=w.text;const owners=segmentsForVerse(v).filter(s=>(s.hebrewTokenIds||[]).includes(w.id));if(!owners.length)sp.style.background='var(--amber-soft)';if(owners.length>1)sp.style.background='var(--red-soft)';src.append(sp,document.createTextNode(' '))});wrap.appendChild(src);segmentsForVerse(v).forEach(s=>{const c=document.createElement('div');c.className='segment-card'+(activeSegmentId===s.id?' selected':'');c.innerHTML=`<div class="segment-top"><span class="segment-title">${esc(shortLine(s.id))}</span><span class="status-badge ${s.status}">${esc(STATUS_LABEL[s.status]||s.status)}</span></div><div class="segment-hebrew">${esc(hebrewText(s.hebrewTokenIds)||'—')}</div><div class="help">Tamil: ${esc(tamilText(s)||'—')}</div>`;c.onclick=()=>{activeSegmentId=s.id;renderSegmentation()};wrap.appendChild(c)});wrap.querySelector('[data-new]').onclick=()=>createSegment(v);root.appendChild(wrap)});renderSegmentEditor()}
function createSegment(v){const id=nextSegmentId(v),segs=segmentsForVerse(v),lineIndex=segs.length?Math.max(...segs.map(s=>s.lineIndex||0))+1:1;commit(()=>state.segments.push({id,verse:String(v),lineIndex,unitType:'colon',hebrewTokenIds:[],tamil:tamilProjection([], '', 'HUMAN_MODIFIED','human'),english:{text:'',method:'human'},...recordBase('HUMAN_MODIFIED','human','editor')}),`${id} created`);activeSegmentId=id;renderAll()}
function renderSegmentEditor(){const title=$('segmentEditorTitle'),body=$('segmentEditorBody'),seg=segmentById(activeSegmentId);if(!seg){title.textContent='Select a segment';body.className='muted';body.textContent='Choose a segment on the left.';return}body.className='';title.textContent=shortLine(seg.id);const v=seg.verse,h=hebrewOrderByVerse[v].map(id=>{const owners=segmentsForVerse(v).filter(s=>(s.hebrewTokenIds||[]).includes(id)),cls=owners.some(s=>s.id===seg.id)?'assigned':owners.length?'other':'unassigned';return`<button type="button" class="assignment-token hebrew ${cls}" data-h="${id}">${esc(hebrewById[id].text)}</button>`}).join(''),t=(tamilOrderByVerse[v]||[]).map(id=>{const owners=segmentsForVerse(v).filter(s=>tamilIds(s).includes(id)),cls=owners.some(s=>s.id===seg.id)?'assigned':owners.length?'other':'unassigned';return`<button type="button" class="assignment-token ${cls}" data-t="${id}">${esc(tamilById[id].text)}</button>`}).join(''),segs=segmentsForVerse(v),idx=segs.findIndex(s=>s.id===seg.id);body.innerHTML=`<p class="help">Click a token to move it into/out of this segment. Source order is preserved.</p><h3>Hebrew assignment</h3><div class="assignment-tray">${h}</div><h3>Tamil mapping</h3><div class="assignment-tray">${t}</div><label>Status<select id="segmentStatusSelect"><option value="UNREVIEWED">Not reviewed</option><option value="AI_PROPOSED">AI proposed</option><option value="HUMAN_MODIFIED">Human modified</option><option value="NEEDS_DISCUSSION">Needs discussion</option><option value="HUMAN_APPROVED">Human approved</option><option value="HUMAN_REJECTED">Human rejected</option></select></label><div class="card-actions"><button id="mergeNextBtn" ${idx<segs.length-1?'':'disabled'}>Merge with next</button><button id="deleteSegmentBtn" class="danger-outline">Delete empty segment</button></div>`;$('segmentStatusSelect').value=seg.status;$('segmentStatusSelect').onchange=e=>commit(()=>setStatus(seg,e.target.value),`${seg.id}: ${STATUS_LABEL[e.target.value]}`);body.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>assignSegmentToken('hebrew',seg.id,b.dataset.h));body.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>assignSegmentToken('tamil',seg.id,b.dataset.t));$('mergeNextBtn').onclick=()=>mergeNext(seg.id);$('deleteSegmentBtn').onclick=()=>deleteEmptySegment(seg.id)}
function assignSegmentToken(lang,segId,tokenId){tokenId=lang==='hebrew'?canonicalHebrewId(tokenId):canonicalTamilId(tokenId);const seg=segmentById(segId),v=seg.verse,order=lang==='hebrew'?hebrewOrderByVerse[v]:tamilOrderByVerse[v],getIds=s=>lang==='hebrew'?(s.hebrewTokenIds||[]):tamilIds(s),already=getIds(seg).includes(tokenId);commit(()=>{const vs=state.segments.filter(s=>s.verse===v),affected=vs.filter(s=>getIds(s).includes(tokenId));vs.forEach(s=>{const ids=ordered(getIds(s).filter(id=>id!==tokenId),order);if(lang==='hebrew')s.hebrewTokenIds=ids;else{s.tamil.tokenIds=ids;s.tamil.text=ids.map(id=>tamilById[id]?.text).filter(Boolean).join(' ');s.tamil.status='HUMAN_MODIFIED';s.tamil.method='human'}});if(!already){const ids=ordered([...getIds(seg),tokenId],order);if(lang==='hebrew')seg.hebrewTokenIds=ids;else{seg.tamil.tokenIds=ids;seg.tamil.text=ids.map(id=>tamilById[id]?.text).filter(Boolean).join(' ');seg.tamil.status='HUMAN_MODIFIED';seg.tamil.method='human'}}uniq([...affected.map(s=>s.id),seg.id]).forEach(id=>{const x=segmentById(id);if(x){x.status=x.status==='HUMAN_APPROVED'?'NEEDS_DISCUSSION':'HUMAN_MODIFIED';x.updatedAt=now()}})},already?`${tokenId} unassigned from ${seg.id}`:`${tokenId} moved to ${seg.id}`)}
function mergeNext(id){const a=segmentById(id),segs=segmentsForVerse(a?.verse),i=segs.findIndex(s=>s.id===id);if(!a||i<0||i===segs.length-1)return;const b=segs[i+1];if(!confirm(`Merge ${b.id} into ${a.id}? References will be updated.`))return;commit(()=>{a.hebrewTokenIds=ordered(uniq([...a.hebrewTokenIds,...b.hebrewTokenIds]),hebrewOrderByVerse[a.verse]);a.tamil.tokenIds=ordered(uniq([...tamilIds(a),...tamilIds(b)]),tamilOrderByVerse[a.verse]);a.tamil.text=a.tamil.tokenIds.map(x=>tamilById[x]?.text).filter(Boolean).join(' ');a.tamil.status='HUMAN_MODIFIED';a.tamil.method='human';a.status='NEEDS_DISCUSSION';state.parallelGroups.forEach(g=>{const changed=(g.lineIds||[]).includes(b.id);g.lineIds=uniq((g.lineIds||[]).map(x=>x===b.id?a.id:x));if(changed)g.status='NEEDS_DISCUSSION'});state.structures.forEach(s=>{let ch=false;if(s.startLineId===b.id){s.startLineId=a.id;ch=true}if(s.endLineId===b.id){s.endLineId=a.id;ch=true}if(ch)s.status='NEEDS_DISCUSSION'});state.segments=state.segments.filter(s=>s.id!==b.id)},`${b.id} merged into ${a.id}`);activeSegmentId=a.id}
function deleteEmptySegment(id){const s=segmentById(id);if(!s)return;if(s.hebrewTokenIds.length||tamilIds(s).length){toast('Only an empty segment can be deleted');return}if(state.parallelGroups.some(g=>g.lineIds.includes(id))||state.structures.some(x=>x.startLineId===id||x.endLineId===id)){toast('Segment is referenced by another annotation');return}commit(()=>state.segments=state.segments.filter(x=>x.id!==id),`${id} deleted`);activeSegmentId=null}
function openQuickGroup(){if(selection.lines.size<2){toast('Select at least two poetic segments first');return}$('quickGroupLines').textContent=[...selection.lines].map(shortLine).join(' ↔ ');$('quickParallelNote').value='';$('groupDialog').showModal()}
function createQuickGroup(e){e.preventDefault();const ids=sortedSegments().filter(s=>selection.lines.has(s.id)).map(s=>s.id);if(ids.length<2)return;const id=nextEntityId('P',state.parallelGroups);commit(()=>state.parallelGroups.push({id,lineIds:ids,type:parallelTypeToV03($('quickParallelType').value),confidence:confidenceToV03($('quickParallelConfidence').value),note:$('quickParallelNote').value.trim(),...recordBase('HUMAN_MODIFIED','human','editor')}),`${id} created and activated`);activeGroupId=id;selection.lines.clear();$('groupDialog').close();renderAll()}
function renderParallelPicker(){const r=$('parallelLinePicker');r.innerHTML='';sortedSegments().forEach(s=>{const row=document.createElement('label');row.className='picker-row'+(selection.lines.has(s.id)?' selected':'');row.innerHTML=`<input type="checkbox" ${selection.lines.has(s.id)?'checked':''}><span class="picker-ref">${esc(shortLine(s.id))}</span><span class="picker-text"><strong>${esc(tamilText(s)||hebrewText(s.hebrewTokenIds))}</strong><br><span class="muted" dir="rtl">${esc(hebrewText(s.hebrewTokenIds))}</span></span>`;row.querySelector('input').onchange=()=>selectLine(s.id);r.appendChild(row)})}
function resetParallelForm(){editingParallelId=null;$('parallelFormTitle').textContent='Create parallel group';$('saveParallelBtn').textContent='Create parallel group';$('cancelParallelEditBtn').classList.add('hidden');$('parallelNote').value='';selection.lines.clear()}
function editParallel(id){const g=groupById(id);editingParallelId=id;selection.lines=new Set(g.lineIds);$('parallelType').value=g.type;$('parallelConfidence').value=g.confidence;$('parallelNote').value=g.note||'';$('parallelFormTitle').textContent=`Edit ${id}`;$('saveParallelBtn').textContent='Save group changes';$('cancelParallelEditBtn').classList.remove('hidden');switchTab('parallelism')}
function saveParallel(){const ids=sortedSegments().filter(s=>selection.lines.has(s.id)).map(s=>s.id);if(ids.length<2){toast('Choose at least two segments');return}const changes={lineIds:ids,type:parallelTypeToV03($('parallelType').value),confidence:confidenceToV03($('parallelConfidence').value),note:$('parallelNote').value.trim()};if(editingParallelId){const g=groupById(editingParallelId);if(setEq(g.lineIds,ids)&&g.type===changes.type&&g.confidence===changes.confidence&&(g.note||'')===changes.note){toast('No changes');return}const was=g.status==='HUMAN_APPROVED';commit(()=>revise(g,changes,'Parallel group edited'),`${g.id} updated${was?' · Needs discussion':''}`);resetParallelForm();renderAll()}else{const id=nextEntityId('P',state.parallelGroups);commit(()=>state.parallelGroups.push({id,...changes,...recordBase('HUMAN_MODIFIED','human','editor')}),`${id} created`);activeGroupId=id;resetParallelForm();renderAll()}}
function deleteParallel(id){if(!confirm(`Delete ${id}? Components will be preserved as unassigned.`))return;commit(()=>{state.parallelGroups=state.parallelGroups.filter(g=>g.id!==id);state.components.forEach(c=>{if(c.parallelGroupId===id){revise(c,{parallelGroupId:null},'Parallel group deleted');c.status='NEEDS_DISCUSSION'}})},`${id} deleted; components preserved`);if(activeGroupId===id)activeGroupId=null}
function renderParallelGroups(){const r=$('parallelGroups');r.innerHTML='';if(!state.parallelGroups.length){r.innerHTML='<p class="muted">No parallel groups yet.</p>';return}state.parallelGroups.forEach(g=>{const c=document.createElement('div');c.className='group-card'+(activeGroupId===g.id?' active':'');c.innerHTML=`<div class="group-top"><span class="group-title">${esc(g.id)} · ${esc(g.type)}</span><span class="pill ${g.status}">${esc(STATUS_LABEL[g.status]||g.status)}</span></div><div class="group-lines">${g.lineIds.map(shortLine).join(' ↔ ')} · ${esc(g.confidence)}</div>${g.note?`<p class="help">${esc(g.note)}</p>`:''}<div class="card-actions"><button data-a="use">Use in Workbench</button><button data-a="edit">Edit</button><button data-a="HUMAN_MODIFIED">Mark modified</button><button data-a="HUMAN_APPROVED">Approve</button>${g.status==='HUMAN_APPROVED'?'<button data-a="reopen">Reopen</button>':''}<button data-a="delete" class="danger-outline">Delete</button></div>`;c.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='use'){activeGroupId=g.id;switchTab('workbench')}else if(a==='edit')editParallel(g.id);else if(a==='delete')deleteParallel(g.id);else if(a==='reopen')commit(()=>setStatus(g,'NEEDS_DISCUSSION'),`${g.id} reopened`);else commit(()=>setStatus(g,a),`${g.id}: ${STATUS_LABEL[a]}`)});r.appendChild(c)})}
function renderComponents(){const f=$('componentFilter'),cur=f.value;f.innerHTML='<option value="">All groups</option><option value="__unassigned">Unassigned</option>'+state.parallelGroups.map(g=>`<option value="${g.id}">${esc(g.id)} · ${esc(g.type)}</option>`).join('');if([...f.options].some(o=>o.value===cur))f.value=cur;let comps=state.components;if(f.value==='__unassigned')comps=comps.filter(c=>!c.parallelGroupId);else if(f.value)comps=comps.filter(c=>c.parallelGroupId===f.value);const issues={};lastValidation.filter(i=>i.entityType==='component').forEach(i=>(issues[i.entityId]||=[]).push(i));const r=$('componentList');r.innerHTML='';if(!comps.length)r.innerHTML='<p class="muted">No components match this filter.</p>';comps.forEach(c=>{const ii=issues[c.id]||[],h=hebrewText(c.hebrewTokenIds),t=tamilIds(c).map(id=>tamilById[id]?.text).filter(Boolean).join(' '),e=document.createElement('div');e.className='component-card'+(ii.some(x=>x.code==='COMPONENT_DUPLICATE')?' duplicate':'')+(ii.some(x=>x.code==='COMPONENT_CONFLICT')?' conflict':'');e.innerHTML=`<div class="component-top"><span class="component-title">${esc(c.id)} · ${esc(c.label)}</span><span class="pill ${c.status}">${esc(STATUS_LABEL[c.status]||c.status)}</span></div><div class="group-lines">Group: ${esc(c.parallelGroupId||'Unassigned')} · revision ${c.revision||1}${ii.length?` · ⚠ ${ii.length} issue(s)`:''}</div><div class="component-preview"><div class="rtl">${esc(h||'—')}</div><div>${esc(t||'—')}</div></div>${c.note?`<p class="help">${esc(c.note)}</p>`:''}<div class="card-actions"><button data-a="edit">Edit</button><button data-a="HUMAN_MODIFIED">Mark modified</button><button data-a="HUMAN_APPROVED">Approve</button>${c.status==='HUMAN_APPROVED'?'<button data-a="reopen">Reopen</button>':''}${c.revisions?.length?'<button data-a="history">History</button>':''}<button data-a="delete" class="danger-outline">Delete</button></div>`;e.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='edit')startEditComponent(c.id);else if(a==='delete')deleteComponent(c.id);else if(a==='reopen')reopenComponent(c.id);else if(a==='history')showHistory('component',c.id);else commit(()=>setStatus(c,a),`${c.id}: ${STATUS_LABEL[a]}`)});r.appendChild(e)});const sum=$('componentSummary');sum.innerHTML=`<dl class="inspector-kv"><dt>Total</dt><dd>${state.components.length}</dd><dt>Approved</dt><dd>${state.components.filter(c=>c.status==='HUMAN_APPROVED').length}</dd><dt>Needs discussion</dt><dd>${state.components.filter(c=>c.status==='NEEDS_DISCUSSION').length}</dd><dt>Unassigned</dt><dd>${state.components.filter(c=>!c.parallelGroupId).length}</dd></dl>`}
function renderStructureSelects(){const opts=sortedSegments().map(s=>`<option value="${s.id}">${esc(shortLine(s.id))} — ${esc((tamilText(s)||hebrewText(s.hebrewTokenIds)).slice(0,50))}</option>`).join(''),a=$('structureStart'),b=$('structureEnd'),p=$('structureParent'),ca=a.value,cb=b.value,cp=p.value;a.innerHTML=opts;b.innerHTML=opts;if([...a.options].some(o=>o.value===ca))a.value=ca;if([...b.options].some(o=>o.value===cb))b.value=cb;p.innerHTML='<option value="">No parent</option>'+state.structures.filter(x=>x.id!==editingStructureId).map(x=>`<option value="${x.id}">${esc(x.label)} · ${esc(x.title)}</option>`).join('');if([...p.options].some(o=>o.value===cp))p.value=cp}
function resetStructureForm(){editingStructureId=null;$('structureFormTitle').textContent='Add structure unit';$('saveStructureBtn').textContent='Add structure unit';$('cancelStructureEditBtn').classList.add('hidden');['structureLabel','structureTitle','structureNote'].forEach(id=>$(id).value='');renderStructureSelects()}
function editStructure(id){const s=structureById(id);editingStructureId=id;renderStructureSelects();$('structureLabel').value=s.label;$('structureTitle').value=s.title;$('structureType').value=s.type;$('structureStart').value=s.startLineId;$('structureEnd').value=s.endLineId;$('structureParent').value=s.parentId||'';$('structureNote').value=s.note||'';$('structureFormTitle').textContent=`Edit ${id}`;$('saveStructureBtn').textContent='Save structure changes';$('cancelStructureEditBtn').classList.remove('hidden');switchTab('structure')}
function saveStructure(){const label=$('structureLabel').value.trim(),title=$('structureTitle').value.trim();if(!label||!title){toast('Add label and title');return}const segs=sortedSegments(),i=segs.findIndex(s=>s.id===$('structureStart').value),j=segs.findIndex(s=>s.id===$('structureEnd').value);if(i<0||j<0||i>j){toast('End segment must follow start segment');return}const changes={label,title,type:structureTypeToV03($('structureType').value),startLineId:$('structureStart').value,endLineId:$('structureEnd').value,parentId:$('structureParent').value||null,note:$('structureNote').value.trim()};if(editingStructureId){const s=structureById(editingStructureId);if(changes.parentId===s.id){toast('A structure cannot parent itself');return}const was=s.status==='HUMAN_APPROVED';commit(()=>revise(s,changes,'Structure edited'),`${s.id} updated${was?' · Needs discussion':''}`);resetStructureForm();renderAll()}else{const id=nextEntityId('S',state.structures);commit(()=>state.structures.push({id,...changes,...recordBase('HUMAN_MODIFIED','human','editor')}),`${id} added`);resetStructureForm();renderAll()}}
function depthFor(s){let d=0,p=s.parentId,seen=new Set();while(p&&!seen.has(p)){seen.add(p);d++;p=structureById(p)?.parentId;if(d>6)break}return Math.min(d,3)}
function deleteStructure(id){if(!confirm(`Delete ${id}? Children will move to top level.`))return;commit(()=>{state.structures=state.structures.filter(s=>s.id!==id);state.structures.forEach(s=>{if(s.parentId===id){s.parentId=null;s.status='NEEDS_DISCUSSION'}})},`${id} deleted`)}
function renderStructures(){const r=$('structureTree');r.innerHTML='';if(!state.structures.length){r.innerHTML='<p class="muted">No structure units yet.</p>';return}const segs=sortedSegments(),arr=[...state.structures].sort((a,b)=>segs.findIndex(s=>s.id===a.startLineId)-segs.findIndex(s=>s.id===b.startLineId));arr.forEach(s=>{const e=document.createElement('div');e.className='structure-item';e.dataset.depth=depthFor(s);e.innerHTML=`<div class="structure-top"><span class="structure-title">${esc(s.label)} — ${esc(s.title)}</span><span class="pill ${s.status}">${esc(s.type)} · ${esc(STATUS_LABEL[s.status]||s.status)}</span></div><div class="group-lines">${esc(shortLine(s.startLineId))} → ${esc(shortLine(s.endLineId))}${s.parentId?` · parent ${esc(s.parentId)}`:''} · rev ${s.revision||1}</div>${s.note?`<p class="help">${esc(s.note)}</p>`:''}<div class="card-actions"><button data-a="edit">Edit</button><button data-a="HUMAN_MODIFIED">Mark modified</button><button data-a="HUMAN_APPROVED">Approve</button>${s.status==='HUMAN_APPROVED'?'<button data-a="reopen">Reopen</button>':''}${s.revisions?.length?'<button data-a="history">History</button>':''}<button data-a="delete" class="danger-outline">Delete</button></div>`;e.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='edit')editStructure(s.id);else if(a==='delete')deleteStructure(s.id);else if(a==='reopen')commit(()=>setStatus(s,'NEEDS_DISCUSSION'),`${s.id} reopened`);else if(a==='history')showHistory('structure',s.id);else commit(()=>setStatus(s,a),`${s.id}: ${STATUS_LABEL[a]}`)});r.appendChild(e)})}
function applyStatus(status){if(!selection.lines.size){toast('Select one or more poetic segments first');return}commit(()=>selection.lines.forEach(id=>{const s=segmentById(id);if(s)setStatus(s,status)}),`Selected segments: ${STATUS_LABEL[status]}`)}
function approveReviewed(){commit(()=>[...state.segments,...state.parallelGroups,...state.components,...state.structures].forEach(x=>{if(x.status==='HUMAN_MODIFIED')x.status='HUMAN_APPROVED'}),'Human-modified annotations approved')}
function approvePsalm(){const issues=validateState(),errors=issues.filter(i=>i.severity==='error'),warnings=issues.filter(i=>i.severity==='warning');if(errors.length){toast(`Cannot approve: ${errors.length} validation error(s)`);switchTab('validation');return}if(warnings.length&&!confirm(`${warnings.length} validation warning(s) remain. Approve anyway?`))return;commit(()=>[...state.segments,...state.parallelGroups,...state.components,...state.structures].forEach(x=>x.status='HUMAN_APPROVED'),'Psalm 1 marked approved')}
function renderValidation(){const e=lastValidation.filter(i=>i.severity==='error').length,w=lastValidation.filter(i=>i.severity==='warning').length,summary=$('validationSummary');summary.innerHTML=`<div class="metric error"><strong>${e}</strong>Errors</div><div class="metric warning"><strong>${w}</strong>Warnings</div><div class="metric ok"><strong>${lastValidation.length?'—':'✓'}</strong>${lastValidation.length?'Review':'Clean'}</div>`;const r=$('validationIssues');r.innerHTML='';if(!lastValidation.length)r.innerHTML='<div class="notice"><strong>Validation clean.</strong> No data-integrity issues detected.</div>';lastValidation.forEach(i=>{const d=document.createElement('div');d.className='validation-item';d.innerHTML=`<span class="severity ${i.severity}">${esc(i.severity)}</span><div><strong>${esc(i.code)}</strong><div class="help">${esc(i.message)}</div></div>${i.entityId?'<button class="small">Go to</button>':''}`;d.querySelector('button')?.addEventListener('click',()=>{if(i.entityType==='component')switchTab('components');else if(i.entityType==='parallelGroup')switchTab('parallelism');else if(i.entityType==='structure')switchTab('structure');else if(i.entityType==='segment'){activeSegmentId=i.entityId;switchTab('segmentation')}});r.appendChild(d)});$('validationBadge').textContent=lastValidation.length;$('validationBadge').classList.toggle('has-issues',lastValidation.length>0)}
function showHistory(type,id){const e=type==='component'?componentById(id):type==='structure'?structureById(id):groupById(id);$('historyTitle').textContent=`${id} · revision ${e.revision||1}`;const r=$('historyBody'),revs=e.revisions||[];r.innerHTML=revs.length?'<div class="history-list"></div>':'<p class="muted">No previous revisions stored.</p>';if(revs.length){const list=r.querySelector('.history-list');revs.forEach((x,i)=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<strong>Revision ${x.revision}</strong><div class="help">${esc(x.change||'Saved')} · ${esc(x.at||'')}</div>${type==='component'?`<button class="small" data-r="${i}">Restore as new revision</button>`:''}`;list.appendChild(d)});list.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>restoreComponentRevision(id,+b.dataset.r))}$('historyDialog').showModal()}
function renderDataset(){$('jsonPreview').textContent=JSON.stringify(state,null,2);$('sourceHashes').innerHTML=Object.values(DATA.meta.sources).map(s=>`<div class="hash-item"><strong>${esc(s.label)}</strong><div class="hash">SHA-256 ${esc(s.sha256)}</div></div>`).join('');$('sourceDialogBody').innerHTML=Object.values(DATA.meta.sources).map(s=>`<div class="source-info-row"><strong>${esc(s.label)}</strong><div class="hash">${esc(s.sha256)}</div></div>`).join('')}
function renderProgress(){const done=state.segments.filter(s=>s.status!=='UNREVIEWED').length;$('progressText').textContent=`${done}/${state.segments.length} segments touched · ${state.parallelGroups.length} group(s) · ${state.components.length} component(s) · ${state.structures.length} structure unit(s)`;$('psalmStatus').textContent=STATUS_LABEL[state.psalmStatus]||state.psalmStatus;$('psalmStatus').className=`status-chip ${state.psalmStatus}`;$('approvePsalmBtn').textContent=state.psalmStatus==='approved'?'✓ Psalm approved':'Approve Psalm'}
function exportJson(){validateState();const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='PSA001.annotations.v0.3.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Annotation JSON exported')}
function showMigrationReport(report,from){$('migrationReport').innerHTML=`<p class="help">Imported into schema v${VERSION}. Source Scripture remains unchanged.</p><div class="migration-list">${(report.length?report:[{kind:'ok',text:`v${from||VERSION} data loaded without migration.`}]).map(x=>`<div class="migration-item ${x.kind||'ok'}">${esc(x.text)}</div>`).join('')}</div><p class="help">Open Validation for remaining data-quality issues.</p>`;$('migrationDialog').showModal()}
function importJson(file){const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(x.book!=='PSA'||+x.psalm!==1)throw Error('Not Psalm 1 annotation JSON');const v=String(x.schemaVersion||''),result=v.startsWith('0.1')?migrateV01(x):v==='0.2.0'?migrateV02(x):v===VERSION?normalizeV03(x):(()=>{throw Error(`Unsupported schema: ${x.schemaVersion||'unknown'}`)})();state=result.state;recomputePsalmStatus();persist();history=[clone(state)];historyIndex=0;activeGroupId=state.parallelGroups[0]?.id||null;editingComponentId=editingParallelId=editingStructureId=activeSegmentId=null;selection={lines:new Set(),hebrew:new Set(),tamil:new Set(),focus:null};renderAll();showMigrationReport(result.report,x.schemaVersion);toast(`Annotations imported as v${VERSION}`)}catch(e){toast('Import failed: '+e.message)}};rd.readAsText(file)}
async function copyJson(){try{await navigator.clipboard.writeText(JSON.stringify(state,null,2));toast('JSON copied')}catch{toast('Clipboard unavailable; use Export')}}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('exportBtn').onclick=exportJson;$('importInput').onchange=e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''};$('clearSelectionBtn').onclick=clearSelection;$('activeGroupSelect').onchange=e=>{activeGroupId=e.target.value||null;renderAll()};$('quickCreateGroupBtn').onclick=openQuickGroup;$('confirmQuickGroupBtn').onclick=createQuickGroup;$('saveComponentBtn').onclick=saveComponentEdit;$('cancelComponentEditBtn').onclick=cancelComponentEdit;$('deleteEditingComponentBtn').onclick=()=>editingComponentId&&deleteComponent(editingComponentId);$('saveParallelBtn').onclick=saveParallel;$('cancelParallelEditBtn').onclick=()=>{resetParallelForm();renderAll()};$('saveStructureBtn').onclick=saveStructure;$('cancelStructureEditBtn').onclick=()=>{resetStructureForm();renderAll()};$('componentFilter').onchange=renderComponents;$('refreshValidationBtn').onclick=()=>{validateState();renderValidation();toast('Validation refreshed')};$('approveReviewedBtn').onclick=approveReviewed;$('approvePsalmBtn').onclick=approvePsalm;$('copyJsonBtn').onclick=copyJson;$('sourceInfoBtn').onclick=()=>$('sourceDialog').showModal();document.querySelectorAll('[data-status-action]').forEach(b=>b.onclick=()=>applyStatus(b.dataset.statusAction));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}})}
if(window.location?.search?.includes('test=1')){window.__TPE_TEST__={getState:()=>clone(state),setActiveGroup:id=>{activeGroupId=id;renderAll()},setLineSelection:ids=>{selection.lines=new Set(ids);renderAll()},setTokenSelection:(h,t)=>{selection.hebrew=new Set((h||[]).map(canonicalHebrewId));selection.tamil=new Set((t||[]).map(canonicalTamilId));renderAll()},createComponentDirect:label=>createComponent(label),startEditComponent,saveComponentEdit,setEditingLabel:l=>{editingComponentLabel=l;renderComponentButtons()},setComponentStatus:(id,s)=>{const c=componentById(id);commit(()=>setStatus(c,s),`test status ${s}`)},assignSegmentToken,createQuickGroup,deleteParallel,saveStructure,restoreComponentRevision,validateState,setQuickGroupFields:(type,confidence,note)=>{$('quickParallelType').value=type;$('quickParallelConfidence').value=confidence;$('quickParallelNote').value=note||''}}}
bind();renderAll();
})();
