const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..'),fixture=process.env.ROSE_COOKIES_FIXTURE||'D:/GPT Lab/19PSAIRVTam-rose-cookies.rose.zip';
if(!fs.existsSync(fixture)){console.log('SKIP Rose Cookies reference fixture not found:',fixture);process.exit(0)}
global.window=global;
vm.runInThisContext(fs.readFileSync(path.join(ROOT,'data/tahot-psalms.js'),'utf8'));
vm.runInThisContext(fs.readFileSync(path.join(ROOT,'data/rose-cookies-schema.js'),'utf8'));
global.ROSE_ZIP=require(path.join(ROOT,'vendor/zip-reader.js'));
global.RESOURCE_DB=require(path.join(ROOT,'resource-db.js'));
const rose=require(path.join(ROOT,'rose-cookies-manager.js')),input=new Uint8Array(fs.readFileSync(fixture)),checks=[];
function ck(value,message){checks.push([!!value,message]);assert.ok(value,message)}
function consecutive(refs){const words=refs.map(x=>+x.slice(8,11)).sort((a,b)=>a-b);return words.every((x,i)=>i===0||x===words[i-1]+1)}
(async()=>{
 const checked=await rose.validatePackage(input);ck(checked.manifest.format==='rose-cookies'&&checked.manifest.formatVersion==='0.1.0','manifest recognized');
 const s=checked.stats;ck(s.psalms===150&&s.tokens===25994&&s.titles===709,'all Psalms, tokens, and title tokens validate');ck(s.linked===23834&&s.unlinked===2160,'tagged and addition token counts validate');ck(s.alignments===17286,'Word Alignment count validates');ck(s.units===17284&&s.support===2149,'Kichadi unit and support-word counts validate');ck(s.markers===17339&&s.realized===16095&&s.implicit===1161&&s.notLocated===83,'semantic marker invariants validate');
 ck(checked.alignments.some(a=>a.sourceRefs.length===1&&a.targetRefs.length>1),'1-to-many alignment remains grouped');ck(checked.alignments.some(a=>a.sourceRefs.length>1&&a.targetRefs.length===1),'many-to-1 alignment remains grouped');ck(checked.alignments.some(a=>a.sourceRefs.length>1&&a.targetRefs.length>1),'many-to-many alignment remains grouped');ck(checked.alignments.some(a=>a.targetRefs.length>1&&!consecutive(a.targetRefs)),'discontiguous alignment remains grouped');
 const split=checked.units.find(u=>u.realizations.length>1&&u.realizations.every(r=>r.span));ck(split&&new Set(split.realizations.map(r=>r.span)).size===split.realizations.length,'split Kichadi realizations remain split');ck(checked.units.some(u=>u.realizations.some(r=>r.marker==='zsem-i'&&!r.targetRefs.length)),'implicit units receive no fabricated target');ck(checked.units.some(u=>u.realizations.some(r=>r.marker==='zsem-nl'&&!r.targetRefs.length)),'not-located units receive no fabricated target');
 const pkg=await rose.importPackage(input,{psalm:2});ck(pkg.stats.tokens===25994,'reference package imports transactionally');const p2=rose.psalmData();ck(p2.psalm===2&&p2.tokens.length>0,'only the active Psalm is loaded');ck(new Set(p2.tokens.map(t=>t.ref)).size===p2.tokens.length,'Tamil Scripture token stream is loaded once');ck(p2.alignments.some(a=>a.sourceRefs.length>1||a.targetRefs.length>1),'active-Psalm relationships preserve units');
 const firstHebrewAlignment=p2.alignBySource.get('190020010011')?.[0];ck(firstHebrewAlignment?.targetRefs.join(',')==='190020010021,190020010081'&&firstHebrewAlignment.targetRefs.map(ref=>p2.byRef.get(ref)?.text).every(Boolean),'Psalm 2 Hebrew selection resolves the complete two-word Tamil relationship');
 const original=await ROSE_ZIP.read(input),aligned=await rose.compatibility('translationCoreAlignedUsfm'),semantic=await rose.compatibility('semanticUsfm');ck(Buffer.compare(Buffer.from(await aligned.data.arrayBuffer()),Buffer.from(await original.get(aligned.path)))===0,'aligned USFM round-trips byte-identically');ck(Buffer.compare(Buffer.from(await semantic.data.arrayBuffer()),Buffer.from(await original.get(semantic.path)))===0,'semantic USFM round-trips byte-identically');
 await rose.init(2);ck(rose.packageInfo()?.packageHash===pkg.packageHash&&rose.psalmData()?.psalm===2,'IndexedDB-compatible resources survive manager restart');
 const unit=p2.units[0],approved=await rose.reviewUnit(unit.id,'HUMAN_APPROVED','checked');ck(approved.status==='HUMAN_APPROVED','human approval is stored as an overlay');const changed=await rose.reviewUnit(unit.id,'HUMAN_APPROVED','changed after approval');ck(changed.status==='NEEDS_DISCUSSION'&&changed.revisions.length===1,'editing approved review preserves revision and reopens review');
 const splitLoaded=p2.units.find(u=>u.realizations.length>1),rid=splitLoaded.realizations[0].realizationId,realizationReview=await rose.reviewUnit(splitLoaded.id,'HUMAN_MODIFIED','split span checked',rid);ck(realizationReview.realizationId===rid,'realization review overlay is keyed separately from its semantic unit');
 const exported=await rose.exportPackage(),exportChecked=await rose.validatePackage(exported.bytes);ck(exportChecked.manifest.reviewedDerivative?.sourcePackageHash===pkg.packageHash,'reviewed Rose Cookies export preserves source provenance');
 const archive=await ROSE_ZIP.read(input),files=[];for(const name of archive.list())files.push({name,data:await archive.get(name)});const tokenPath=checked.manifest.layers.scripture.tokenIndex,badFiles=files.map(x=>x.name===tokenPath?{name:x.name,data:new Uint8Array([...x.data.slice(0,-1),x.data[x.data.length-1]^1])}:x),bad=ROSE_ZIP.write(badFiles);let rejected=false;try{await rose.importPackage(bad)}catch(error){rejected=error.code==='SHA256_MISMATCH'}ck(rejected&&rose.packageInfo().packageHash===pkg.packageHash,'bad SHA-256 rejects atomically and leaves active package untouched');
 const unsafe=new Uint8Array(input),needle=Buffer.from('README.md'),replacement=Buffer.from('../bad.md');let replacements=0;for(let i=0;i<=unsafe.length-needle.length;i++)if(Buffer.from(unsafe.slice(i,i+needle.length)).equals(needle)){unsafe.set(replacement,i);replacements++}let unsafeRejected=false;try{await ROSE_ZIP.read(unsafe)}catch(error){unsafeRejected=/Unsafe ZIP path/.test(error.message)}ck(replacements>=2&&unsafeRejected,'unsafe ZIP path is rejected');
 let conflict=false;try{await rose.validatePackage(input,{existingSources:[{code:'ta',name:'Tamil IRV',psalms:{1:{1:'மாற்றப்பட்ட உரை'}}}]})}catch(error){conflict=error.code==='SCRIPTURE_CONFLICT'&&error.details[0].psalm===1}ck(conflict,'changed Tamil Scripture triggers a token-level conflict');
 console.log(`PASS ${checks.length}/${checks.length}`);for(const[,message]of checks)console.log('  OK',message);console.log('ROSE COOKIES REFERENCE PACKAGE TESTS PASSED');
})().catch(error=>{console.error(error);process.exit(1)});
